"""Add Product tables

Revision ID: 94b496eff2b5
Revises: 37dd14aa63df
Create Date: 2024-10-15 11:33:23.363599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94b496eff2b5'
down_revision = '37dd14aa63df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_number', sa.Integer(), nullable=False))
        batch_op.drop_column('processor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('items_number')

    # ### end Alembic commands ###
